SELECT * FROM STORE WHERE ID > 100 && ID < 2500;
SELECT * FROM STORE WHERE PROFILE >= 1 && PROFILE <=3 && ID>10000;
SELECT * FROM STORE WHERE (IdRubro = 1 || IdRubro = 2 )&& LOCATE("Banco",NAME)>0;
SELECT MAX(ID),NAME FROM STORE;
SELECT MIN(LAT),NAME FROM STORE;

UPDATE STORE SET NAME = "Banco Nacion de la Argentina" WHERE NAME = "Banco Nacion";
UPDATE STORE SET NAME = "Musical Norte" WHERE NAME = "AGB";
UPDATE STORE SET LNG = -57.000001 WHERE NAME = "Astor";